rec_main:
    resource: "@RecMainBundle/Controller/"
    type:     annotation
    prefix:   /

msi_search:
    resource: "@MsiSearchBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

homepage:
    pattern:  /
    defaults: { _controller: RecMainBundle:Home:index }

# fos_user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# msi_admin

msi_admin_loader:
    resource: .
    type: msi_admin

msi_admin:
    resource: "@MsiAdminBundle/Resources/config/routing.yml"

# msi_cms:
#     resource: "@MsiCmsBundle/Resources/config/routing.yml"

msi_cms:
    resource: "@MsiCmsBundle/Controller"
    type: annotation

msi_cms_page_show:
    pattern: /{slug}
    defaults: { _controller: MsiCmsBundle:Page:show, slug: ~ }
